# Basic
title: Robot
subtitle: 兴趣使然的图灵机
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 人生一世，不过于苦海作乐。
creator: <a href="http://leont.ml">@Leon</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Tools, description: My tools, url: 'http://tools.leont.ml'}
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
#    weibo: onevcat
#    github: onevcat
#    twitter: onevcat
#    gplus: 107108267983477358170
    mail: 3433538213@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman
