encoding: utf-8

# SEO相关信息
title: Mr.R0boter's Blog
description: 兴趣使然的图灵机
keywords: R0boter,Blog,Python,Html,JavaScript,C,PHP,ShellScript
author: Mr.R0boter
#footerText: "Copyright © 2016 皖ICP备16016174号"

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude:
  [
    "CNAME",
    "README.md",
    "LICENSE",
    "_site",
    "dist",
    "Gemfile",
    "Gemfile.lock",
    "cli.bat",
    "dist.tar.gz",
  ]

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: "http://www.roboter.ga"
baseurl: ""

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 友情链接
links:
  - title: TMaize Blog
    url: https://blog.tmaize.net
